IF
	OR(2)
		Global("LyrosJob","GLOBAL",3)
		Dead("lyros") // Xzar
	Exists("Rylock")
	Global("RylockLeavesHarperDoor","AR0300",0)
THEN
	RESPONSE #100
		SetGlobal("RylockLeavesHarperDoor","AR0300",1)
		CloseDoor("DOOR0308")
		Lock("DOOR0308")
		ActionOverride("Rylock",EscapeArea())
END

IF
	Global("LyrosSpawn","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("LyrosSpawn","GLOBAL",2)
		CreateCreature("XZAR",[2372.2475],0) // Xzar
END


