IF
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	Global("Shield","LOCALS",0)
THEN
	RESPONSE #100
		ApplySpell(Myself,WIZARD_FIRE_SHIELD_RED)
		SetGlobal("Shield","LOCALS",1)
END

IF
	See(NearestEnemyOf(Myself))
	StateCheck(Myself,STATE_INVISIBLE)
	Global("EfreetiFireball","LOCALS",0)
THEN
	RESPONSE #100
		ReallyForceSpell(NearestEnemyOf(Myself),WIZARD_FIREBALL)
		SetGlobal("EfreetiFireball","LOCALS",1)
END

